baseURL = "/"
title = "Flux"
enableRobotsTXT = true
enableEmoji = true

# Language configuration
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

theme = ["docsy"]

# Markup settings
# Ref: https://gohugo.io/getting-started/configuration-markup#goldmark
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "friendly"
[markup.parser]
autoHeadingID = true
autoHeadingIDType = "github"

# Provide .LastMod values
enableGitInfo = true

[languages]
[languages.en]
languageName = "English"
languageCode = "en"
time_format_default = "2006-01-02"
time_format_blog = "2006-01-02"
contentDir = "content/en"

[permalinks]
  blog = "/:section/:year/:month/:slug/"

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]


[params]
description          = "Open and extensible continuous delivery solution for Kubernetes."
copyright            = "The Flux authors"
github_repo          = "https://github.com/fluxcd/website"
github_branch        = "main"
github_project_repo  = "https://github.com/fluxcd/flux2"
slack                = "https://cloud-native.slack.com/messages/flux"
support              = "/support"
font_awesome_version = "5.9.0"
images               = ["img/flux-social.png"]

# Enable Algolia DocSearch
algolia_docsearch = true
offlineSearch = false


#version_menu         = "Docs"
#version              = "current"
#url_latest_version   = "/docs/"
#
## Add your release versions here
#[[params.versions]]
#  version = "current"
#  url = "/docs"
#
#[[params.versions]]
#  version = "legacy"
#  url = "/legacy"
#

[params.taxonomy]
taxonomyCloud = ["blog"]


[params.logos]
navbar = "flux-horizontal-white.png"
hero   = "flux-horizontal-color.png"
footer = "flux-stacked-white.png"
cncf   = "cncf-color.png"



[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_menu_truncate = 1000

#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

[params.ui.readingtime]
enable = false

[params.markmap]
enable = true


[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.

[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/fluxcd"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name ="LinkedIn"
	url = "https://linkedin.com/groups/8985374"
	icon = "fab fa-linkedin"
	desc = "Join the Flux Community group on LinkedIn!"
[[params.links.user]]
	name = "RSS Feed"
	url = "/blog/index.xml"
	icon = "fa fa-rss"
	desc = "Subscribe to the RSS feed of our blog!"
[[params.links.user]]
	name = "Support"
	url = "/support"
	icon = "fas fa-comments"
	desc = "Subscribe to the RSS feed of our blog!"


# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "Flux project on GitHub"
	url = "https://github.com/fluxcd"
	icon = "fab fa-github"
	desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://cloud-native.slack.com/messages/flux"
	icon = "fab fa-slack"
	desc = "Chat with other project developers"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://lists.cncf.io/g/cncf-flux-dev"
	icon = "fa fa-envelope"
	desc = "Discuss development issues around the project"
[[params.links.developer]]
	name="Flux YouTube channel"
	url = "https://www.youtube.com/channel/UCoZxt-YMhGHb20ZkvcCc5KA"
	icon = "fab fa-youtube"
	desc = "Recordings of past Flux dev meetings"



[[menus.main]]
url = "/docs"
name = "Docs"
weight = 1


[[menus.main]]
identifier = "Project"
name = "Project"
weight = 20

[[menus.main]]
name = "Code of Conduct"
parent = "Project"
url = "https://github.com/fluxcd/community/blob/main/CODE_OF_CONDUCT.md"
weight = 1

[[menus.main]]
name = "Resources"
parent = "Project"
url = "/resources"
weight = 5

[[menus.main]]
name = "Support"
parent = "Project"
url = "/support"
weight = 10

[[menus.main]]
name = "Community"
parent = "Project"
url = "/community"
weight = 20

[[menus.main]]
name = "Contributing"
parent = "Project"
url = "/docs/contributing"
weight = 30

[[menus.main]]
name = "Governance"
parent = "Project"
url = "/governance"
weight = 40

[[menus.main]]
name = "Roadmap"
parent = "Project"
url = "/roadmap"
weight = 50

[[menus.main]]
name = "Security"
parent = "Project"
url = "/security"
weight = 60

[[menus.main]]
name = "Branding"
parent = "Project"
url = "https://github.com/cncf/artwork/blob/master/examples/incubating.md#flux-logos"
weight = 9999

[[menus.main]]
name = "Adopters"
url = "/adopters"
weight = 80

[[menus.main]]
name = "Integrations"
url = "/integrations"
weight = 90

[[menus.main]]
url = "https://github.com/fluxcd/flux2"
name = "Github"
pre = "<i class='fab fa-github'></i> "
weight = 100


